<a href="https://colab.research.google.com/github/Bartosztakon/Bartosztakon/blob/main/Dzia%C5%82ania_na_macierzach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array ([1.2, 2.1, 3.6], dtype= float)
A.dtype
print(A)

B = np.array([True, False])
A.dtype

[1.2 2.1 3.6]


dtype('float64')

In [ ]:
np.zeros(shape=(4, 10), dtype= 'float')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.full(shape=(4, 10), fill_value=10.5, dtype= 'float')

array([[10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5]])

In [ ]:
np.arange(100,0, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [ ]:
np.linspace(start=0, stop=1, num=21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
import numpy as np
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A+B)
print(B-B)
print(A*B)
print(A/B)

[6 0 7 4]
[0 0 0 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [9]:
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [10]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [14]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [16]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [17]:
X @ Y

array([[  3,   6],
       [-12,   0]])